// ----------------------------------------------------------------------

export const _secteurs = [
  {
    id: '1',
    title: 'Accompagnement au montage et à la mise en œuvre des projets de Développement',
    description: 'Nos populations cibles sont généralement moins outillées pour traduire en projet les idées de projets. Le CREPID s\'engage à accompagner de façon participative les communautés, organisations, entreprises et individus dans l\'identification des problèmes et la mise sur pied des stratégies appropriées de solution.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Accompagnement au montage de projets/Gemini_Generated_Image_y33if7y33if7y33i.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Accompagnement au montage de projets/Gemini_Generated_Image_y33if7y33if7y33i.png',
    createdAt: new Date('2024-01-15'),
    duration: '5 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Accompagnement',
    favorited: false,
    actions: [
      'Diagnostics participatifs et élaboration des stratégies de développement',
      'La recherche-action',
      'Élaboration des projets de développement',
      'Réalisation des études qui permettent aux commanditaires d\'avoir des données et des scénarios possibles pour une prise de décision',
    ],
  },
  {
    id: '2',
    title: 'Formations pratiques dans divers domaines d\'activité agricoles, d\'élevage et d\'artisanat',
    description: 'Le CREPID accueille les apprenants et les affecte immédiatement auprès des exploitations de leur choix pour une formation essentiellement pratique. La durée de la formation est variable selon la filière choisie. Au terme de la formation, l\'apprenant ouvre sa propre exploitation et reste sous le suivi/encadrement du CREPID pendant au moins un cycle de production au terme duquel il dispose d\'une bonne expérience.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Formations pratiques agricoles/formation_agricole_1.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Formations pratiques agricoles/formation_agricole_1.png',
    createdAt: new Date('2024-01-20'),
    duration: '8 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Formation',
    favorited: false,
    sousSections: [
      {
        titre: 'Mise en place et conduite d\'un verger d\'avocatiers',
        contenu: 'Avocatier : Culture à moindre risque et peu exigeante. Plus de 80 000 FCFA à gagner par plant dès l\'année de croisière. Appui-conseil et accompagnement à la création et à la conduite des vergers. Visitez la ferme pilote d\'application du CREPID à Bansoa dans l\'Ouest du Cameroun, Département de la Menoua, localité de Konché, 288 km de la capitale Yaoundé.',
      },
      {
        titre: 'Mise en place et conduite des exploitations de maïs de contre-saison',
        contenu: 'Appui-conseil et accompagnement à la création d\'exploitation. Visitez la ferme pilote d\'application du CREPID pour la culture des semences de maïs à Bansoa dans l\'Ouest du Cameroun, Département de la Menoua, localité de Banock, 288 km de la capitale Yaoundé.',
      },
      {
        titre: 'Mise en place et formation en conduite d\'exploitation porcine',
        contenu: 'Race Landrace, Race Large White ou Yorkshire.',
      },
      {
        titre: 'Mise en place et formation en conduite d\'exploitations avicoles',
        contenu: '',
      },
      {
        titre: 'Formation en apiculture',
        contenu: 'Rucher et récolte du miel, collecte et traitement du miel, extraction grâce au pressoir à miel.',
      },
      {
        titre: 'Mise en place et formation en conduite de bananier plantain',
        contenu: 'Ferme pilote d\'application du CREPID, production de la banane plantain.',
      },
      {
        titre: 'Mise en place et formation en transformation et conservation des fruits',
        contenu: 'Atelier de transformation et conservation des fruits et autres produits agricoles.',
      },
    ],
  },
  {
    id: '3',
    title: 'Accompagnement à la formulation, à la mise en œuvre et au suivi et évaluation des projets de développement',
    description: 'À partir d\'une planification stratégique et opérationnelle, le CREPID suit des projets, des populations et institutions bénéficiaires. Le CREPID accompagne également les structures dans la mise en place des unités de suivi interne.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Développement organisationnel/image1.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Développement organisationnel/image1.png',
    createdAt: new Date('2024-02-01'),
    duration: '6 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Suivi-Évaluation',
    favorited: false,
  },
  {
    id: '4',
    title: 'Études et recherches pour la promotion des technologies innovantes',
    description: 'Le CREPID conçoit de nouveaux modèles technologiques et les met à la disposition des populations cibles. Ces modèles sont testés en milieu réel et vulgarisés auprès des populations.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Études et recherches innovantes/image copy 3.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Études et recherches innovantes/image copy 3.png',
    createdAt: new Date('2024-02-10'),
    duration: '7 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Recherche',
    favorited: false,
    domaines: [
      'Gestion des ressources naturelles : régénération des raphiales en milieu réel',
      'Bâtiment : promotion de la brique de terre stabilisée dans l\'habitat',
      'Transformation des produits forestiers non ligneux : valorisation du bambou de Chine en ameublement',
    ],
  },
  {
    id: '5',
    title: 'Animation des réflexions et des formations',
    description: 'Le CREPID facilite les moments de réflexion et organise des formations au profit des organisations, entreprises et individus. Il produit également des supports audiovisuels pour la formation et la communication.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Animation et formations/image.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Animation et formations/image.png',
    createdAt: new Date('2024-02-15'),
    duration: '5 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Formation',
    favorited: false,
    actions: [
      'Organisation et facilitation des ateliers et rencontres de renforcement des capacités techniques',
      'Accompagnement au renforcement de la dynamique interne des groupes',
      'Production de supports audiovisuels pour la formation et la communication (documentations, affiches, boîtes à images, etc.)',
      'Formation des formateurs sur la GAR à Kaélé, Extrême-Nord du Cameroun',
    ],
  },
  {
    id: '6',
    title: 'Développement organisationnel',
    description: 'Comment permettre à votre organisation d\'utiliser rationnellement ses ressources internes et externes pour faciliter le progrès ? Le CREPID accompagne les structures dans un processus planifié de développement organisationnel.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Développement organisationnel/image2.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Développement organisationnel/image2.png',
    createdAt: new Date('2024-02-20'),
    duration: '6 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Développement',
    favorited: false,
  },
  {
    id: '7',
    title: 'Diagnostic participatif et renforcement des capacités des organisations paysannes',
    description: 'Diagnostic participatif au développement du groupe ADIBE, localité de Banock, groupement Bansoa dans la région de l\'Ouest Cameroun.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Développement organisationnel/image1.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Développement organisationnel/image1.png',
    createdAt: new Date('2024-03-01'),
    duration: '4 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Diagnostic',
    favorited: false,
  },
  {
    id: '8',
    title: 'Accompagnement au processus d\'organisation et d\'autopromotion des populations démunies des milieux urbains',
    description: 'Le CREPID apporte un appui à l\'autopromotion des populations démunies des milieux urbains par l\'organisation en réseau d\'acteurs de développement par filière de production et le développement de l\'artisanat et des petites activités.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Autopromotion populations urbaines/image.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Autopromotion populations urbaines/image.png',
    createdAt: new Date('2024-03-10'),
    duration: '7 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Développement',
    favorited: false,
    actions: [
      'Organisation des populations du secteur informel en réseau d\'acteurs de développement par filière de production',
      'Identification participative des problèmes communs et mise en place des stratégies communes de résolution',
      'Développement de l\'artisanat et des petites activités d\'agriculture et d\'élevage urbain et périurbain',
      'Processus de passage des activités du stade informel vers le stade de véritable entreprise',
    ],
    illustration: 'Jeunes dans un atelier d\'artisanat en mécanique de fabrication. Accompagnement des jeunes en déperdition scolaire au processus d\'auto-emploi.',
  },
  {
    id: '9',
    title: 'Accompagnement à l\'organisation et professionnalisation des producteurs',
    description: 'Développement de stratégies qui suscitent l\'esprit de groupe et favorisent la professionnalisation dans les filières de production.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Professionnalisation producteurs/watering-1501209_1920.webp',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Professionnalisation producteurs/watering-1501209_1920.webp',
    createdAt: new Date('2024-03-15'),
    duration: '6 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Professionnalisation',
    favorited: false,
    actions: [
      'Appui à la création des organisations de producteurs',
      'Appui à la restructuration des organisations existantes',
      'Facilitation à la mise sur pied des coopératives et des entreprises du secteur agropastoral et autres',
      'Réalisation des diagnostics participatifs et organisation des formations conséquentes',
      'Accompagnement des organisations de producteurs à l\'élaboration de leur plan d\'action et suivi dans leur mise en œuvre',
    ],
  },
  {
    id: '10',
    title: 'Conception et réalisation d\'outils de communication',
    description: 'Le CREPID réalise et propose des messages, supports et outils divers pour transmettre des idées et faire connaître des produits.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Outils de communication/Gemini_Generated_Image_hkr54phkr54phkr5.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Outils de communication/Gemini_Generated_Image_hkr54phkr54phkr5.png',
    createdAt: new Date('2024-03-20'),
    duration: '5 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Communication',
    favorited: false,
  },
  {
    id: '11',
    title: 'Épargne, microcrédits et financement des microprojets ruraux et urbains',
    description: 'Développement de stratégies et de mécanismes de mobilisation des fonds pour le financement des activités des populations.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Microcrédits et financement/image.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Microcrédits et financement/image.png',
    createdAt: new Date('2024-04-01'),
    duration: '6 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Financement',
    favorited: false,
    actions: [
      'Aider à la mise sur pied des sources informelles d\'épargne et de crédit (tontine, djangui) et renforcer les capacités des membres pour leur gestion efficace',
      'Répertorier les sources possibles de subventions locales ou extérieures pouvant être accordées aux petits producteurs et les accompagner dans la démarche de demande',
      'Organiser les diagnostics participatifs et le redressement des structures informelles de financement',
    ],
  },
  {
    id: '12',
    title: 'Genre et Développement',
    description: 'Le CREPID anime des réflexions sur l\'approche genre et développe des stratégies pour impliquer davantage la femme dans la vie économique, sociale et culturelle.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Genre et Développement/Gemini_Generated_Image_hkr54phkr54phkr5.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Genre et Développement/Gemini_Generated_Image_hkr54phkr54phkr5.png',
    createdAt: new Date('2024-04-10'),
    duration: '4 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Genre',
    favorited: false,
  },
  {
    id: '13',
    title: 'Développement de la pêche et de l\'aquaculture',
    description: 'L\'objet visé est d\'amener les populations rurales à comprendre l\'importance de l\'aquaculture et de la pêche comme activité susceptible d\'améliorer leur bien-être. Grâce aux compétences disponibles en la matière et en collaboration avec les partenaires locaux et extérieurs, le CREPID s\'est engagé dans les activités suivantes :',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Pêche et aquaculture/image.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Pêche et aquaculture/image.png',
    createdAt: new Date('2024-04-15'),
    duration: '7 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Aquaculture',
    favorited: false,
    actions: [
      'Animation et sensibilisation des populations sur le bien-fondé de la pêche et de l\'aquaculture',
      'Accompagnement dans la sélection des espèces appropriées',
      'Accompagnement dans le choix des sites de pêche et d\'élevage',
      'Formation sur les divers aspects des techniques de production : construction des étangs, production des alevins, nutrition au stade larvaire et adulte, technique de récolte et de conservation, fertilisation et gestion de la productivité naturelle, compte d\'exploitation prévisionnel de gestion',
    ],
    illustration: 'Expédition scientifique dans le fleuve Logone et Chari. Travaux conduits par le Directeur du CREPID (en tricot et chapeau blanc).',
  },
  {
    id: '14',
    title: 'Gestion durable des ressources naturelles',
    description: 'Suite aux contraintes de la démographie galopante, la dégradation des ressources naturelles est de plus en plus inquiétante au courant de cette dernière décennie et nécessite une attention particulière. Pour cette raison, le CREPID s\'est engagé sur la voie de recherche et de l\'identification des stratégies de gestion durables de ces ressources.',
    coverImg: '/assets/images/crepid/Domaines d\'Intervention/Gestion durable des ressources naturelles/image.png',
    heroImg: '/assets/images/crepid/Domaines d\'Intervention/Gestion durable des ressources naturelles/image.png',
    createdAt: new Date('2024-04-20'),
    duration: '6 min',
    author: { name: 'CREPID', picture: '/assets/images/avatar/avatar_1.jpg', role: 'Organisation', about: 'Centre de Recherche et d\'Expertise pour le Développement Intégré et Durable', quotes: 'Ensemble pour un développement durable' },
    category: 'Environnement',
    favorited: false,
    actions: [
      'Développement des stratégies d\'aménagement et de gestion participative des écosystèmes fragiles (bas-fonds et terrains marécageux, terrains à risque d\'éboulement)',
      'Développement des stratégies de régénération et de conservation des ressources génétiques en danger d\'extinction (raphiales, bambous de Chine, diverses essences de plantes cultivées et sauvages, diverses races d\'animaux domestiques et sauvages)',
      'Appui au développement de l\'agroforesterie',
      'Appui au développement de la foresterie communautaire',
    ],
    illustrations: [
      'Régénération du bambou de Chine, essai en milieu paysan, conduit par le Directeur du CREPID (courbé, en blouson jean délavé)',
      'Exploitation rationnelle des ressources naturelles : valorisation du bambou de Chine et des produits forestiers non ligneux en artisanat',
      'Captage et aménagement d\'une source d\'eau',
      'Protection de l\'environnement : gestion des emballages des pesticides',
    ],
  },
];
